language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy
install:
  - cd ../
  - git clone -b master https://github.com/iElectric/mr.bob.git
  - cd mr.bob
  - python setup.py install
  - cd ../bobtemplates.openbsd/
  - python setup.py develop
  - easy_install . bobtemplates.openbsd[test]
script:
  - make test -k
after_success:
  - easy_install coveralls
  - coveralls
